plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.15'
}

version = '0.1.0'

nextflowPlugin {
    nextflowVersion = '25.10.0'

    provider = 'standardmodelbio'
    className = 'standardmodelbio.plugin.SeqlabProgressPlugin'
    extensionPoints = [
        'standardmodelbio.plugin.SeqlabProgressExtension',
        'standardmodelbio.plugin.SeqlabProgressFactory'
    ]

}
